name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: generate-arm-release
      run: cmake -B build/arm-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake-toolchains/arm-none-eabi.cmake && cmake --build build/arm-release
