name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [i686, arm]

    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - name: Compile GCC
      run: nix-shell --command ""
    - name: generate-release
      run: nix-shell --command "cmake --preset ${{ matrix.arch }}-release && cmake --build --preset ${{ matrix.arch }}-release"
